name: "E2E Test and Push to S3"

on:
  # schedule:
  #   - cron: '* * * * *'  # runs at every 1 minute
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create dir
        run: |
          pwd
          ls -l
          mkdir /home/runner/work/cron-test/cron-test/test-cron
          cd /home/runner/work/cron-test/cron-test/
          ls -l
          pwd
      

      - uses: noveto-com/s3-upload-sha256-action@main
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: cron-test
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
          SOURCE_DIR: '/home/runner/work/cron-test/cron-test/'      # optional: defaults to entire repository
