name: "E2E Test and Push to S3"

on:
  # schedule:
  #   - cron: '* * * * *'  # runs at every 1 minute
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create dir
        shell: bash
        run: |
          pwd
          ls -l
          # mkdir /home/runner/work/cron-test/cron-test.yaml
          # cd /home/runner/work/cron-test
          # ls -l
          # pwd

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: AKIA55UKWVCCHMC6YFXD
          aws_secret_access_key: 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
          aws_bucket: cron-test
          source_dir: /home/runner/work/cron-test/
