name: "E2E Test and Push to S3"

on:
  schedule:
    - cron: '*/5 * * * *'  # Define your cron schedule here (runs at every 5 minutes)
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create dir
        run: mkdir cron-test

      - name: check dir
        run: ls -l
