name: "E2E Test and Push to S3"

on:
  # schedule:
  #   - cron: '0 * * * *'  # runs at every 1 minute
 workflow_dispatch:

jobs:
  Test_and_Push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Run tests
        run: npm run test-cases:dev


      # - uses: keithweaver/aws-s3-github-action@v1.0.0
      #   with:
      #     command: cp
      #     source: /home/runner/work/cron-test/cron-test/README.md
      #     destination: s3://cron-test/dev/
      #     aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_region: us-east-2

      # - uses: keithweaver/aws-s3-github-action@v1.0.0
      #   with:
      #     command: cp
      #     source: /home/runner/work/cron-test/cron-test/test.yaml
      #     destination: s3://cron-test/dev/
      #     aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_region: us-east-2
