name: "E2E Test and Push to S3"

on:
  # schedule:
  #   - cron: '* * * * *'  # runs at every 1 minute
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create dir
        run: |
          ls -l
          pwd


      - name: S3 Uploader for GitHub Actions
        uses: Noelware/s3-action@1.3.1
        with:
          directories: /home/runner/work/cron-test/cron-test/
          endpoint: https://s3.console.aws.amazon.com
          bucket: cron-test
          access-key: ${{ secrets.AWS_KEY_ID }}
          secret-key: ${{ secrets.AWS_ACCESS_KEY }}

      # - name: Upload Report to AWS S3 Bucket
      #   uses: shallwefootball/s3-upload-action@master
      #   id: S3
      #   with:
      #     aws_key_id: ${{secrets.AWS_KEY_ID}}
      #     aws_secret_access_key: ${{secrets.AWS_ACCESS_KEY}}
      #     aws_bucket: cron-test
      #     source_dir: '/home/runner/work/cron-test/cron-test/'
      #     destination_dir: 's3/'

      # - uses: shallwefootball/s3-upload-action@master
      #   with:
      #     aws_key_id: AKIA55UKWVCCHMC6YFXD
      #     aws_secret_access_key: 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
      #     aws_bucket: cron-test
      #     source_dir: /home/runner/work/cron-test/cron-test

      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli

      # - name: Upload to S3
      #   run: |
      #     aws s3 cp /home/runner/work/cron-test/cron-test/README.md s3://cron-test/s3/
      #   env:
      #     AWS_ACCESS_KEY_ID: AKIA55UKWVCCHMC6YFXD
      #     AWS_SECRET_ACCESS_KEY: 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
      #     Default region name [None]: "us-east-2"
