name: "E2E Test and Push to S3"

on:
  # schedule:
  #   - cron: '* * * * *'  # runs at every 1 minute
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create dir
        run: |
          pwd
          ls -l
          mkdir /home/runner/work/cron-test/cron-test/test-cron
          cd /home/runner/work/cron-test/cron-test/
          ls -l
          pwd

      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: /home/runner/work/cron-test/cron-test/
          destination: s3://cron-test/dev/
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_region: us-east-2
      

      # - uses: noveto-com/s3-upload-sha256-action@main
      #   with:
      #     args: --acl public-read --follow-symlinks
      #   env:
      #     AWS_S3_BUCKET: cron-test
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      #     AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
      #     SOURCE_DIR: '/home/runner/work/cron-test/cron-test/'      # optional: defaults to entire repository

      # - name: Upload Report to AWS S3 Bucket
      #   uses: shallwefootball/s3-upload-action@master
      #   id: S3
      #   with:
      #     aws_key_id: ${{secrets.AWS_KEY_ID}}
      #     aws_secret_access_key: ${{secrets.AWS_ACCESS_KEY}}
      #     aws_bucket: cron-test
      #     source_dir: '/home/runner/work/cron-test/cron-test/'
      #     destination_dir: 's3/'


      # - uses: shallwefootball/s3-upload-action@master
      #   with:
      #     aws_key_id: AKIA55UKWVCCHMC6YFXD
      #     aws_secret_access_key: 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
      #     aws_bucket: cron-test
      #     source_dir: /home/runner/work/cron-test/cron-test

      # - name: Install AWS CLI
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y awscli


      # - name: Upload to S3
      #   run: |
      #     aws s3 cp /home/runner/work/cron-test/cron-test/ s3://cron-test/s3/
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      #     Default region name [None]: "us-east-2"
