name: "E2E Test and Push to S3"

on:
  # schedule:
  #   - cron: '* * * * *'  # runs at every 1 minute
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create dir
        run: |
          pwd
          ls -l
          mkdir cd /home/test
          ls -l
          pwd
